### ISSUE TITLE
Add more favicons

### ISSUE THREAD

**Issue by phrakture** [wlonk/wheretofind.me#50] opened 2019-01-12 14:42 UTC
Pinterest, Slack, and WordPress are pretty good ones, I think. More icons will make it easier to glance at

**Comment by wlonk** [comment] 2019-01-14 06:46
Closing as duplicate of #17.

The intent (and for Mastodon, Diaspora*, etc, this becomes particularly acute) is to guess the right icon, but let a user select one if the guess is wrong, when they add the link. In the meantime, I've added a lot more brand icons tonight, so hopefully that mitigates this issue for now.

**Closed by wlonk** 2019-01-14 06:46 UTC
